name: Publish

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.119.0"
          extended: true

      - name: Build Hugo Site
        env:
          HUGO_PARAMS_GOOGLEANALYTICS: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          HUGO_PARAMS_RECAPTCHAKEY: ${{ secrets.RECAPTCHA_KEY }}
          HUGO_PARAMS_HUBSPOTCODE: ${{ secrets.HUBSPOT_CODE }}
        run: hugo --minify

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: rotational.io